INSERT INTO archetypes (id, class_id, name, description, replaces, features, class_skills_added, class_skills_removed, spells_per_day_override) VALUES
('', '', 'Resistencia Extrema', 'Reduces el daño de fuego y frío en la mitad.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Agarre Brutal', 'Ganas bonificación de +2 a maniobras de combate para agarrar.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Lealtad Urbana', 'Ganas habilidades de clase sociales adicionales.', '[]', '[]', 'diplomacy,knowledge_local,linguistics', 'handle_animal,survival', NULL),
('', '', 'Mole Blindada', 'Reduces la penalización de armadura a la velocidad en 5 pies.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Arco Arcano', 'Tratas una espada elegida como arma de duelista arcano.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Gracia de Corte', 'Ganas bonificación a Diplomacia y Engaño igual a la mitad de tu nivel.', '[]', '[]', 'knowledge_nobility', NULL, NULL),
('', '', 'Carterista', 'Ganas Sleight of Hand como habilidad de clase y la mitad del nivel como bonificación.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Aliado Divino', 'Las criaturas que convocas ganan bonificadores extra por cada 3 niveles.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Magia de Dominio Intensificada', 'Los conjuros de tu dominio se lanzan como si fueras 4 niveles más alto.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Vínculo con el Templo', 'Mientras estés en terreno sagrado tu nivel de clérigo cuenta +4 para poderes de dominio.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Aura de Podredumbre', 'Las criaturas adyacentes sufren penalización a las salvaciones de Fortaleza.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Adaptación Subterránea', 'Ignoras la penalización de moverse en terreno difícil subterráneo.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Llamada de la Tormenta', 'Convocas una tormenta menor que dura horas igual a tu nivel.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Puntería Precisa', 'Ignoras la bonificación de cobertura del objetivo.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Ataque con Dos Armas Mejorado', 'Reduces la penalización por luchar con dos armas en 1.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Maestría de Arma', 'Ganas Enfoque en Arma y Especialización en Arma con tu arma elegida gratis.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Maniobra Táctica', 'Ganas +2 a maniobras de combate cuando usas un movimiento para estudiar al oponente.', '[]', '[]', 'knowledge_arcana,knowledge_dungeoneering,knowledge_nature,knowledge_planes,knowledge_religion', NULL, NULL),
('', '', 'Perfección de Estilo', 'Puedes entrar en tres estilos de combate a la vez.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Flecha Ki', 'Puedes gastar puntos ki para añadir daño a tus flechas.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Cerrojo Experto', 'Cuando inmovilizas a un oponente puedes hacer una tirada de daño sin arma.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Santuario Divino', 'Creas un aura de protección de 10 pies que otorga bonificación de sagrado a saves.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Cirujano de Combate', 'Puedes usar Manos Puestas como acción rápida para estabilizar a un aliado.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Poder Divino Ampliado', 'Usas el nivel completo de paladín para determinar los efectos del dominio.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Vínculo de Manada', 'Tus compañeros actúan coordinados, ganando bonificadores cuando están adyacentes.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Terreno Adaptado', 'Tus bonificadores de terreno favorito se aplican a un radio mayor e incluyen a aliados.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Movimiento Táctico', 'Puedes moverte sin provocar ataques de oportunidad una vez por ronda.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Disparar y Correr', 'Puedes disparar y moverte sin penalización en el mismo turno.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Carga Furtiva', 'Puedes aplicar ataque furtivo al cargar.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Gracia de Duelo', 'Añades tu modificador de Carisma a los checks de Intimidar contra oponentes que hayas herido.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Golpe Aterrador', 'Con ataque furtivo puedes asustar al objetivo en lugar de dañarlo.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Escalar Ágil', 'Tu velocidad de escalar es igual a tu velocidad base de tierra.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Tatuaje Mágico', 'Puedes activar efectos de conjuro almacenados en tus tatuajes.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Hechizos Potenciados', 'Los hechizos de ambos linajes se lanzan a nivel +1.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Trampa Detectora', 'Puedes detectar trampas mágicas como un ladrón de nivel igual al tuyo.', '[]', '[]', 'knowledge_arcana,linguistics,perception', NULL, NULL),
('', '', 'Supresión de Conjuro', 'Puedes suprimir un conjuro o efecto mágico activo como dispel magic, 1/día por cada 6 niveles.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Convocación Potenciada', 'Las criaturas que convocas con conjuros de invocación ganan beneficios adicionales.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Ojo del Adivino', 'Puedes usar clairvoyance/clairaudience a voluntad sobre lugares que hayas visitado antes.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Sugestión Arcana', 'Cuando falla la TS de un encantamiento tuyo, el objetivo queda desorientado 1 ronda en cambio.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Evocación Potenciada', 'Añades mod. INT de daño adicional a cualquier conjuro de evocación que cause daño (una vez por conjuro).', '[]', '[]', NULL, NULL, NULL),
('', '', 'Velo Persistente', 'Las ilusiones que creas duran el doble y su CD de salvación aumenta en 1.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Animación Rápida', 'Puedes crear no-muertos con animate dead sin material component y uno más por día.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Cambio de Forma Físico', 'Cuando lanzas un conjuro de transmutación de forma, añades +2 a FUE o DES durante la duración.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Celeridad del Viento', 'Aumentas tu velocidad de movimiento en 10 pies. A nivel 10, puedes volar con velocidad de vuelo media.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Piel de Piedra', 'Obtienes RD 1/— que aumenta en 1 por cada 4 niveles de mago.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Elemental del Fuego', 'Ganas inmunidad al fuego y tu daño con conjuros de fuego ignora la resistencia al fuego de 5 o menos.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Forma Acuosa', 'Puedes breathe water, nadas con velocidad 30 pies, y ganas RD 5/slashing cuando estás bajo el agua.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Explosión Potenciada', 'Puedes elegir el tipo de energía de la bomba (fuego, frío, electricidad o ácido) al crearla.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Pergamino Blindado', 'Cuando te impacta un conjuro o ataque mágico, puedes gastar un pergamino para reducir el daño a la mitad.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Toque de Oscuridad', 'Tu toque apaga fuentes de luz no mágicas y puede causar ceguera temporal (Fort niega, 1 ronda/nivel).', '[]', '[]', NULL, NULL, NULL),
('', '', 'Recarga Mágica', 'Puedes recargar tu pistola arcana como acción libre 3 + mod. INT veces al día sin usar munición física.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Explotación Arcana', 'Aprendes explotaciones arcanas del Arcanista. Inicias con una y obtienes otra a nivel 3 y cada 2 niveles después.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Consejo de los Libros', 'Añades la mitad de tu nivel a checks de Conocimiento sobre magia y puedes "recordar" conjuros ya lanzados como si tuvieras el talento Lore Master.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Favores del Patrono', 'Tu patrono te concede uno de sus poderes innatos que puedes usar 1/día.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Dominio de Pecado', 'Tu especialización está asociada a uno de los siete pecados capitales Thassilonianos; ganas poderes temáticos únicos relacionados con él.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Escudo Arcano Defensivo', 'Puedes crear una cúpula de fuerza mágica que protege un área de 30 pies de diámetro de ataques de asedio durante 1 hora/día.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Resistencia Mágica', 'Ganas resistencia a conjuros = 10 + nivel mientras estás en furia.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Golpe Aplastante', 'Con armas de gran tamaño, el daño de crítico se multiplica por uno adicional.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Potencia Salvaje', 'Mientras estás en furia, añades el doble de tu bonificador de moral al daño cuerpo a cuerpo.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Transformación Salvaje', 'A partir del nivel 6, la transformación lunar durante la furia se vuelve más pronunciada: ganas ataques naturales adicionales.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Furia Elemental', 'Durante la furia, tus ataques cuerpo a cuerpo causan 1d6 de daño elemental adicional del tipo elegido.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Evasión', 'Ganas Evasión como el ladrón.', '[]', '[]', 'disable_device,knowledge_dungeoneering', NULL, NULL),
('', '', 'Serenata de la Verdad', 'Mantienes una bardic performance que fuerza a los que la escuchan a superar Vol o no pueden mentir durante su duración.', '[]', '[]', 'knowledge_local,linguistics', NULL, NULL),
('', '', 'Truco de Distracción', 'Como acción estándar, creas una distracción que otorga bonificación flanking a un aliado hasta el inicio de tu siguiente turno.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Furia Inspirada', 'Los aliados afectados por tu inspire courage pueden entrar en un estado de berserker menor (+2 FUE, −1 CA) durante la duración.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Voz de la Tormenta', 'Tu bardic performance de inspire courage añade daño eléctrico igual a la bonificación que ya otorga.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Lore Divino', 'Puedes identificar conjuros y efectos mágicos como si usaras identify automáticamente.', '[]', '[]', 'knowledge_arcana,knowledge_dungeoneering,knowledge_nature,knowledge_planes', NULL, NULL),
('', '', 'Maestría Marcial', 'Ganas Golpe Poderoso o Combate con Dos Armas como talento adicional de combate, aunque no cumplas los requisitos.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Maniobra Sagrada', 'Puedes gastar usos de Canalizar Energía para que todos tus aliados en 30 pies hagan ataques de oportunidad contra un enemigo que designes.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Curación Masiva', 'Tus conjuros de curación curan el máximo posible cuando los lanzas sobre criaturas que están a 0 PV o menos.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Fe Independiente', 'Eres menos vulnerable a efectos que perjudican a seguidores de una deidad específica.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Palabra de Dios', 'Tu sermón puede afectar a no-creyentes como hold person (Vol niega) mientras mantienes la performance.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Forma Urbana', 'Puedes transformarte en un humanoide común además de en animales, manteniendo tus poderes de druida.', '[]', '[]', 'diplomacy,knowledge_local', 'knowledge_nature,survival', NULL),
('', '', 'Adaptación Rápida', 'Cambias tu terreno favorito activo como acción gratuita una vez al día.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Llamada del Mar', '1/día convocas una tormenta de agua dulce o marina de 60 pies de radio que dificulta la visión y el movimiento.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Forma Ártica', 'Puedes transformarte en animales del ártico (osos polares, lobos árticos, focas) ganando sus immunidades al frío.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Maestro de la Jungla', 'Moverse a través de vegetación natural difícil no te cuesta movimiento adicional y no dejas rastros.', '[]', '[]', 'knowledge_nature,stealth', NULL, NULL),
('', '', 'Animación Vegetal', '1/día animas una planta de tamaño Mediano o menor como si usara liveoak. A nivel 8 puedes animar plantas Grandes.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Carga Mejorada', 'No provacas ataques de oportunidad al cargar y puedes girar hasta 90° durante la carga.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Muro de Escudos', 'Si tú y un aliado lleváis escudos y estáis adyacentes, la bonificación de escudo de ambos aumenta en 2.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Actuación de Combate', 'Tratas Actuación como habilidad de clase y puedes añadir mod. CAR a las maniobras de combate para aturdir.', '[]', '[]', 'perform', NULL, NULL),
('', '', 'Acometida Aérea', 'Puedes hacer una carga desde montura voladora con penalización de solo −1 al ataque y daño doble.', '[]', '[]', 'ride', NULL, NULL),
('', '', 'Escudo Inexpugnable', 'Puedes usar el escudo de torre para obtener cobertura total como acción de movimiento en lugar de estándar.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Resistencia al Dolor', 'Cuando llegas a 0 PV, haces una tirada de Fortaleza (CD 15). Si la superas, sigues combatiendo con el estado fatigado en lugar de caer.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Flujo Perfecto', 'Una vez por ronda, cuando esquivas un ataque, puedes hacer un ataque de oportunidad contra el atacante como acción libre.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Terrifying Strike', 'Al gastar 1 punto ki, un golpe causa que el objetivo quede asustado durante 1d4 rondas (Vol niega).', '[]', '[]', NULL, NULL, NULL),
('', '', 'Ki del Arma', 'Puedes gastar puntos ki para añadir propiedades mágicas (impactante, exacta, etc.) a tu arma perfecta durante 1 minuto.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Carga Ki', 'Cuando cargas montado y gastas 1 punto ki, el multiplicador de daño de carga aumenta en 1 y no provocas ataques de oportunidad.', '[]', '[]', 'ride', NULL, NULL),
('', '', 'Meditación Profunda', 'Si meditas 1 hora, puedes lanzar augury o, a nivel 10, divination como poder sobrenatural.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Estratega Sagrado', 'Cuando usas Trabajo en Equipo Divino, también añades un bonificador de competencia de +2 a las tiradas de ataque de los aliados afectados.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Carga Celestial', 'Tu montura y tú podéis cargar como si fuerais una sola criatura. La CA no se reduce durante la carga.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Aura de Purificación', 'Los no-muertos en 10 pies sufren −2 a todas las tiradas y los efectos que controlan no-muertos en el aura fallan automáticamente.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Golpe de Luz Sagrada', 'Gastas 2 usos de Manos Puestas para causar daño de luz sagrada = 1d6/4 niveles en explosión de 10 pies (Ref ½).', '[]', '[]', NULL, NULL, NULL),
('', '', 'Picado Coordinado', 'Cuando tu halcón ataca un objetivo, tus ataques de proyectil contra ese objetivo ganan +2 al ataque y daño hasta el inicio de tu siguiente turno.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Infiltración Perfecta', 'Mientras te haces pasar por una criatura de tu tipo de Enemigo Favorito, ganas una de sus habilidades raciales a elección.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Trampa Mágica', 'Puedes crear trampas con efectos de conjuro de ranger (duración concentrada). El conjuro se activa cuando una criatura detona la trampa.', '[]', '[]', 'disable_device', NULL, NULL),
('', '', 'Vínculo con la Tierra', 'Puedes lanzar conjuros de terreno (hallucinatory terrain, move earth) como poderes sobrenaturales 1/día en tu territorio.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Instinto Primario', 'Ganas scent (olfato) permanente y +4 a Percepción basada en olfato. No puedes sorprenderte mientras estés consciente.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Velocidad del Cuchillo', 'Puedes sacar una daga oculta como acción libre y lanzarla como parte del mismo ataque.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Abordaje', 'Cuando balanceas con una cuerda o saltas a otra embarcación, puedes hacer un ataque de aturdimiento gratis al aterrizar.', '[]', '[]', 'swim,profession', NULL, NULL),
('', '', 'Veneno Potenciado', 'La CD de los venenos que aplicas aumenta en 2 y los venenos de inicio rápido tienen una segunda tirada de salvación.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Extracción de Información', 'Cuando interrogas a alguien durante 10 minutos, puedes hacer una tirada de Sentir Motivaciones con +5. Si la superas, obtienes una verdad que no quería revelar.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Cara de Poker', 'Eres inmune a detect thoughts y lie detection. Puedes engañar a detectores mágicos de mentiras con una tirada de Engaño contra CD 25.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Robo Perfecto', 'Puedes intentar robar objetos mágicos atados o malditos. Si lo consigues, el objeto no detecta el robo hasta que el dueño lo compruebe activamente.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Sangre Salvaje', 'Una vez al día puedes "activar" tu mutación salvaje para doblar la eficacia de un poder de linaje durante 1 ronda.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Magia del Bosque', 'Añades conjuros de druida de nivel 1 a tu lista de conjuros conocidos. A nivel 7 añades conjuros de nivel 2.', '[]', '[]', 'knowledge_nature,survival', NULL, NULL),
('', '', 'Resistencia Celestial', 'Ganas resistencia al fuego y ácido 5, y resistencia a la electricidad y frío 5. A nivel 9 aumentan a 10.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Versatilidad Arcana', '1/día puedes lanzar un conjuro usando la bonificación de un linaje secundario aunque no sea tu linaje activo.', '[]', '[]', NULL, NULL, NULL),
('', '', 'Máscara del Sacerdote', 'Añades cure light wounds y bless a tu lista de conjuros conocidos como conjuros arcanos. Ganas +4 a Engaño para mantener tu disfraz religioso.', '[]', '[]', NULL, NULL, NULL);