-- Skills seed
INSERT INTO skills (id, name, ability, is_class_skill, has_armor_check_penalty, description)
VALUES
  ('acrobatics', 'Acrobacias', 'dexterity', true, true, 'Saltos, volteretas, equilibrismo y rodar para evitar ataques.'),
  ('escape_artist', 'Artista del Escape', 'dexterity', true, true, 'Escapar de ataduras, cuerdas y apretones.'),
  ('spellcraft', 'Competencia con Hechizos', 'intelligence', true, false, 'Identificar spells, entender wéricas y crear items mágicos.'),
  ('knowledge_arcana', 'Conocimiento (Arcano)', 'intelligence', true, false, 'Conocimiento de magia, spells, dragones y seres planares.'),
  ('knowledge_dungeoneering', 'Conocimiento (Dungeon)', 'intelligence', true, false, 'Conocimiento de subterráneos, monstruos y geografía.'),
  ('knowledge_geography', 'Conocimiento (Geografía)', 'intelligence', true, false, 'Conocimiento de tierras, mapas, clima y ríos.'),
  ('knowledge_history', 'Conocimiento (Historia)', 'intelligence', true, false, 'Conocimiento de eventos históricos, personas y civilizaciones.'),
  ('knowledge_engineering', 'Conocimiento (Ingeniería)', 'intelligence', true, false, 'Conocimiento de arquitectura, ingeniería y edificios.'),
  ('knowledge_local', 'Conocimiento (Local)', 'intelligence', true, false, 'Conocimiento de una región específica, rumores, leyendas.'),
  ('knowledge_nature', 'Conocimiento (Naturaleza)', 'intelligence', true, false, 'Conocimiento de animales, plantas, tierras y clima.'),
  ('knowledge_nobility', 'Conocimiento (Nobleza)', 'intelligence', true, false, 'Conocimiento de relaciones nobiliarias, protocolos y heraldos.'),
  ('knowledge_planes', 'Conocimiento (Planos)', 'intelligence', true, false, 'Conocimiento de planos exteriores,-inner, y seres planares.'),
  ('knowledge_religion', 'Conocimiento (Religión)', 'intelligence', true, false, 'Conocimiento de dioses, rituales, muertos vivientes y filosofía.'),
  ('disable_device', 'Desactivar Mecanismos', 'dexterity', true, false, 'Abrir cerraduras, desactivar trampas y saboteer mecanismos.'),
  ('diplomacy', 'Diplomacia', 'charisma', true, false, 'Influenciar, calmar, persuadevir y hacer buenas primeras impresiones.'),
  ('disguise', 'Disfrazarse', 'charisma', true, false, 'Crear disfraces y fingir ser otra persona.'),
  ('bluff', 'Engañar', 'charisma', true, false, 'Mentir convincentemente, engañar, disimular y fast talk.'),
  ('appraise', 'Evaluar', 'intelligence', true, false, 'Determinar el valor de objetos valiosos y detectar trampas.'),
  ('perform', 'Interpretación', 'charisma', true, false, 'Actuar, cantar, bailar, tocar instrumentos, contar historias.'),
  ('intimidate', 'Intimidar', 'charisma', true, false, 'Influenciar a través de amenazas y comportamiento hostil.'),
  ('sleight_of_hand', 'Juego de Manos', 'dexterity', true, true, 'Robar carterismo, plantar objetos y trucos de magia.'),
  ('linguistics', 'Lingüística', 'intelligence', true, false, 'Conocimiento de idiomas y códigos, descifrar escritura.'),
  ('ride', 'Montar', 'dexterity', true, true, 'Montar animales, dirigir monturas y realizar trucos.'),
  ('swim', 'Nadar', 'strength', true, true, 'Nadar y resistir ser arrastrado por el agua.'),
  ('craft', 'Oficio', 'intelligence', true, false, 'Crear objetos. Se debe especificar un tipo de crafting.'),
  ('perception', 'Percepción', 'wisdom', true, false, 'Notar cosas, escuchar, buscar y percibir algo oculto.'),
  ('profession', 'Profesión', 'wisdom', true, false, 'Trabajo remunerado. Se debe especificar una profesión.'),
  ('heal', 'Sanar', 'wisdom', true, false, 'Curar heridas, identificar venenos y enfermedades.'),
  ('sense_motive', 'Sentir Motivaciones', 'wisdom', true, false, 'Detectar mentiras, motivaciones ocultas y engaños.'),
  ('stealth', 'Sigilo', 'dexterity', true, true, 'Ocultarse, moverse sin ser visto y passar desapercibido.'),
  ('survival', 'Supervivencia', 'wisdom', true, false, 'Rastrear, encontrar provisiones, predecir clima, sobrevivir.'),
  ('handle_animal', 'Trato con Animales', 'charisma', true, false, 'Domesticar, calmar y comandar animales.'),
  ('climb', 'Trepar', 'strength', true, true, 'Escalar superficies verticales y superficies inclinadas.'),
  ('use_magic_device', 'Usar Dispositivo Magic', 'charisma', true, false, 'Activar objetos mágicos sin ser el lanzador.'),
  ('fly', 'Volar', 'dexterity', true, true, 'Maniobrar mientras se vuela.')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  ability = EXCLUDED.ability,
  is_class_skill = EXCLUDED.is_class_skill,
  has_armor_check_penalty = EXCLUDED.has_armor_check_penalty,
  description = EXCLUDED.description;